file(MAKE_DIRECTORY "${WORK}")
set(goal "num_ranks 32\n")
foreach(rank RANGE 0 31)
    string(APPEND goal "rank ${rank} {\n")
    if(rank EQUAL 0)
        string(APPEND goal "l1: send 65536b to 31 tag 7\n")
    elseif(rank EQUAL 31)
        string(APPEND goal "l1: recv 65536b from 0 tag 7\n")
    endif()
    string(APPEND goal "}\n")
endforeach()
file(WRITE "${WORK}/no_loss.goal" "${goal}")
execute_process(COMMAND "${TXT2BIN}" -i "${WORK}/no_loss.goal" -o "${WORK}/no_loss.bin"
                RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "txt2bin failed: ${output} ${error}")
endif()
foreach(mode default none headroom)
    set(flags)
    if(NOT mode STREQUAL "default")
        list(APPEND flags -rnic_cn_control_recovery "${mode}")
    endif()
    execute_process(COMMAND "${RNIC}" -goal "${WORK}/no_loss.bin"
        -linkspeed_bps 400000000000 -rnic_profile rnic-cn
        -completion_csv "${WORK}/${mode}.csv" ${flags}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
    file(WRITE "${WORK}/${mode}.log" "${output}\n${error}")
    if(NOT status EQUAL 0 OR NOT output MATCHES "physical_quiescence=verified"
        OR NOT output MATCHES "rnic_cn_control_headroom_admissions=0")
        message(FATAL_ERROR "${mode} failed: ${output} ${error}")
    endif()
    file(SHA256 "${WORK}/${mode}.csv" digest)
    if(mode STREQUAL "default")
        set(expected "${digest}")
    elseif(NOT digest STREQUAL expected)
        message(FATAL_ERROR "${mode} changed no-loss completion CSV bytes")
    endif()
endforeach()
message(STATUS "default, explicit none and headroom completion CSVs are byte-identical")
